name: Deploy doc5s Staging
on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          clean: false  # Prevents deletion of untracked files
          
      - name: Copy Code
        run: 
          cp -R ./* ~/smsdev/code

      - name: Deploy code
        run: |
          cd ~/smsdev/code
          docker compose -f ./deploy/docker-compose.yml up -d --build
      
      - name: Clean dangling data
        run:
          docker system prune -f